export const BITTREX_ORDERBOOK = 'BITTREX_ORDERBOOK';
export const BITTREX_SUMMARY = 'BITTREX_SUMMARY';
export const BINANCE_ORDERBOOK = 'BINANCE_ORDERBOOK';
export const BINANCE_SUMMARY = 'BINANCE_SUMMARY';
export const BINANCE_CANDLESTICK = 'BINANCE_CANDLESTICK';
export const BITTREX_CANDLESTICK = 'BITTREX_CANDLESTICK';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERTS = 'SET_ALERTS';
export const SET_TRADEVOL = 'SET_TRADEVOL';
export const SET_THRESHOLD = 'SET_THRESHOLD';
export const BINANCE_STATUS = 'BINANCE_STATUS';
export const BITTREX_STATUS = 'BITTREX_STATUS';

export const SWITCH_TAB = 'SWITCH_TAB';
