export const INITIALIZE = 'INITIALIZE';

export const UPDATE_CORE_INFO = 'UPDATE_CORE_INFO';
export const UPDATE_THEME = 'UPDATE_THEME';

export const BITTREX_ORDERBOOK = 'BITTREX_ORDERBOOK';
export const BITTREX_24 = 'BITTREX_24';
export const BINANCE_ORDERBOOK = 'BINANCE_ORDERBOOK';
export const BINANCE_24 = 'BINANCE_24';
export const MARKET_DATA_LOADED = 'MARKET_DATA_LOADED';
export const BINANCE_CANDLESTICK = 'BINANCE_CANDLESTICK';
export const BITTREX_CANDLESTICK = 'BITTREX_CANDLESTICK';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERTS = 'SET_ALERTS';
export const SET_TRADEVOL = 'SET_TRADEVOL';
export const SET_THRESHOLD = 'SET_THRESHOLD';
export const BINANCE_WALLET_STATUS = 'BINANCE_WALLET_STATUS';
export const BITTREX_WALLET_STATUS = 'BITTREX_WALLET_STATUS';
